[phases.setup]
nixPkgs = ["python310"]
providers = []

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && streamlit run app.py --server.port ${PORT:-8501} --server.address 0.0.0.0 --server.headless true"
